# Generated by Django 2.2.1 on 2019-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed', models.CharField(max_length=300)),
            ],
        ),
    ]
